/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "box_2.h"

void print_box(dimensions dims, box_results *b_res, mail_dims m_dims, float *price)
{
	printf("Box with dimensions:\n\tLenght: %f\n\tWidth: %f\n\tHeight: %f\n",
			dims.length, dims.width, dims.height);
	printf("Has Surface area: %f\n", b_res->surface);
	printf("Has Volume: %f\n", b_res->volume);
	printf("And mass: %f\n", m_dims.mass);
	printf("Will cost $%f to ship\n", price);
	return;
}

int main (int argc, char *argv[])
{
	char *host;
	CLIENT *client;
	dimensions dims;
	box_results *b_res;
	mail_dims m_dims;
	float *price;

	if (argc != 6) {
		printf("usage: %s server_host length width height mass\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	dims.length = atof(argv[2]);
	dims.width = atof(argv[3]);
	dims.height = atof(argv[4]);

	client = clnt_create(host, RPC_BOX, BOXVERSION2, "udp");
	if (client == NULL)
	{
		clnt_pcreateerror(host);
		exit(EXIT_FAILURE);
	}

	b_res = box_calc_2(&dims, client);
	if (b_res == NULL)
	{
		clnt_perror(client, host);
		exit(EXIT_FAILURE);
	}
	
	m_dims.volume = b_res->volume;
	m_dims.mass = atof(argv[5]);

	price = mail_calc_2(&m_dims, client);
	if (price == NULL)
	{
		clnt_perror(client, host);
		exit(EXIT_FAILURE);
	}
	print_box(dims, b_res, m_dims, price);
	
	clnt_destroy(client);

	return 0;
}
